### PR TITLE
Claim Block sell option and  switch between vanilla or EMF fishing

### PR DESCRIPTION
**Pull request by akex06**
Added an option sell-type: in config.yml which switches between selling fish for money or claim blocks (Grief Prevention)

### CODE REVIEW

**Comment by akex06** [comment]
Just encountered a bug related to selling blocks, I am fixing it, dont merge yet

**Comment by akex06** [comment]
> This does not work on version:
What does not work?

**Comment by noaskers** [comment]
When i enable the claimblock option i don't get the claimblocks

**Comment by akex06** [comment]
I'll look into it

**Comment by noaskers** [comment]
Any solutions? yet to be found?

**Pull request merged**
