### PR TITLE
Improve Reward System

### PR DESCRIPTION
**Pull request by FireML**
- Replaces the RewardType enum with an interface to allow third party plugins to register their own.
- Moves each reward to its own class file, which implements the RewardType interface.
- New RewardTypes are logged to console when registered:
```
[06:51:55 INFO]: [EvenMoreFish] Registered COMMAND RewardType by Oheers
[06:51:55 INFO]: [EvenMoreFish] Registered EFFECT RewardType by Oheers
[06:51:55 INFO]: [EvenMoreFish] Registered HEALTH RewardType by Oheers
[06:51:55 INFO]: [EvenMoreFish] Registered HUNGER RewardType by Oheers
[06:51:55 INFO]: [EvenMoreFish] Registered ITEM RewardType by Oheers
[06:51:55 INFO]: [EvenMoreFish] Registered MESSAGE RewardType by Oheers
[06:51:55 INFO]: [EvenMoreFish] Registered MONEY RewardType by Oheers
[06:51:55 INFO]: [EvenMoreFish] Registered PERMISSION RewardType by FireML
[06:51:55 INFO]: [EvenMoreFish] Registered PLAYER_POINTS RewardType by FireML
```
- Fixes a few potential bugs in each reward by adding more checks.
- Retains the original way of registering your own rewards by firing the event if a valid RewardType is not found.
- The Health RewardType now accounts for the player's max health attribute.
- Adds EXP RewardType `- "EXP:100"`

All reward types work just like they used to as we can see in the console log below:
```
  1:
    - "COMMAND:give {player} diamond 5"
    - "MESSAGE:&aCongratulations for coming 1st!"
    # Can't contain decimals.
    - "MONEY:5000"
    - "EFFECT:SPEED,2,5"
    - "ITEM:DIAMOND,2"
    - "HEALTH:-5"
    - "HUNGER:-5"
    - "PERMISSION:test.123"
    - "PLAYER_POINTS:100"
```
```
[06:52:41 INFO]: [EvenMoreFish] [STDOUT] give FireML diamond 5
[06:52:41 INFO]: Giving 5 of Diamond () to FireML
[06:52:41 INFO]: [EvenMoreFish] [STDOUT] &aCongratulations for coming 1st!
[06:52:41 INFO]: 5000
[06:52:41 INFO]: PotionEffect{amplifier=2, duration=100, type=CraftPotionEffectType[minecraft:speed], ambient=true, particles=true, icon=true, hiddenEffect=null}
[06:52:41 INFO]: ItemStack{DIAMOND x 2}
[06:52:41 INFO]: -5
[06:52:41 INFO]: -5
[06:52:41 INFO]: [EvenMoreFish] [STDOUT] test.123
[06:52:41 INFO]: 100
```

### CODE REVIEW

**Comment by FireML** [comment]
Also, an example of how a third party plugin would register one:
```
public class WarpRewardType implements RewardType {

    @Override
    public void doReward(@NotNull Player player, @NotNull String key, @NotNull String value, int quantity) {
        Warp warp = Data.getInstance().getWarp(value);
        if (warp != null) {
            warp.tryVisit(player, true);
        }
    }

    @Override
    public @NotNull String getIdentifier() {
        return "WARP";
    }

    @Override
    public @NotNull String getAuthor() {
        return "FireML";
    }

    @Override
    public @NotNull JavaPlugin getPlugin() {
        return Plugin.getInstance();
    }

}
```
`new WarpRewardType().register();`

**Review by sarhatabaot — CHANGES_REQUESTED** [review]
In this case, anything in the "reward" package should be moved into the api module.
It should be done in such a way that is mostly abstract. We don't want plugin to rely on the core module of EMF.

**Comment by FireML** [comment]
Alright, I'll give that a go

**Comment by FireML** [comment]
I've moved RewardManager, RewardType, Reward, and EMFRewardEvent to the API module.

I've added the following:
- EMFRewardsLoadEvent - Fired when the plugin is enabled, and when the server is finished loading.
- The RewardManager is now loaded in a main class method, where the RewardTypes are also registered
- RewardManager is now unloaded when the plugin is disabled

Rewards appear to still work correctly:
```
[10:44:29 INFO]: FireML issued server command: /emf admin competition start 5
[10:44:34 INFO]: Giving 5 of Diamond () to FireML
```

**Review by sarhatabaot — APPROVED** [review]
Lgtm, great work!

**Pull request merged**
