### PR TITLE
PlayerPoints Integration

### PR DESCRIPTION
**Pull request by FireML**
Suggested in #271 

Due to the way PlayerPoints works, we can only give it ints. Everything I've done here should account for that.

- Adds the Economy class and an EconomyType enum so we can use the correct provider.
- Adds a method to the Economy class which will format values so players don't get the wrong information. 
> To be specific, this will floor any doubles when PlayerPoints is used and return 0.0 when there is no Economy provider.
- Fixes the ConfigUpdater because it wasn't working properly.
- Adds better logging to the ConfigUpdater so admins know exactly what's going on.

This was designed in a way that should make adding other economy types quite easy, so i might add more if i feel like it / see requests for it.

### CODE REVIEW

**Comment by FireML** [comment]
Example usage of the code I just wrote
```
      catch-event:
        - "PLAYER_POINTS:100"
```

**Comment by FireML** [comment]
- Adds PlayerPoints as a potential reward type:
```
      catch-event:
        - "PLAYER_POINTS:100"
```

**Review by sarhatabaot — APPROVED** [review]
Lgtm, great work on this one 😁

**Comment by noaskers** [comment]
If possible would be cool to add support for this one aswell:
https://www.spigotmc.org/resources/coinsengine-economy-and-virtual-currencies.84121/

**Comment by FireML** [comment]
> If possible would be cool to add support for this one aswell: https://www.spigotmc.org/resources/coinsengine-economy-and-virtual-currencies.84121/
> 
> And it would also be cool if we can give these after selling fish at the shop ;)

Unfortunately that plugin doesn't have a repository for its API, so i won't be able to add it right now. I'd recommend asking the dev if there will be a maven repository at some point so this can be done.

**Pull request merged**
