### PR TITLE
Multiple Fixes

### PR DESCRIPTION
**Pull request by FireML**
Fixes the following:
- Items showing up as raw materials when they shouldn't
- Denizen item support
- ArrayIndexOutOfBoundsException when you have an invalid potion effect

Adds the following:
- A warning when a fish's potion effect is invalid.
- Support for custom items in the random material lists

### CODE REVIEW

**Comment by FireML** [comment]
These have been tested and work as intended as far as i can tell

**Review by sarhatabaot — APPROVED** [review]
Lgtm

**Comment by sarhatabaot** [comment]
I can't merge this since I'm on mobile. @Oheers can you take a look and resolve the conflicts?

**Comment by FireML** [comment]
I resolved it

**Pull request merged**
