### PR TITLE
Re-add use-this-casing rarity config option and some fixes

### PR DESCRIPTION
**Pull request by FireML**
I'm not sure why this was removed, but we've had multiple people mention it in the discord server.

Also updates the default competition config to make sure we don't "break" servers updating from 1.6.11.17 (broadcast-range defaulted to 100, when it was global in 1.6.11.17)

### CODE REVIEW

**Comment by noaskers** [comment]
Can confirm this solve issues I had!

**Review by sarhatabaot — CHANGES_REQUESTED** [review]
Changing getDisplayName() to return just the displayname it self creates some code duplication that can be avoided.

If we want to access the actual displayname, i.e. for a null check in doLorePrep, we can do so directly via this.displayName.

Aside from that all good!

**Comment by FireML** [comment]
Sorted ☺️

**Review by sarhatabaot — APPROVED** [review]
lgtm!

**Pull request merged**
