### PR TITLE
Use InventoryGUI for the plugin's GUIs.

### PR DESCRIPTION
**Pull request by FireML**
Aims to replace all GUI handling with the InventoryGUI library.
Edit: I will leave the Xmas 2022 GUI untouched, as that is no longer used.

This one will probably take me a while to complete.

### CODE REVIEW

**Comment by FireML** [comment]
The Sell GUI is now handled with InventoryGUI and it all appears to be working correctly. Here's a list of changes i made:
- Removed InteractHandler.java - Now unused
- Changed the SellGUI constructor - Removed the boolean, as you now need to use the open method instead.
- Added a config for the GUI layout, and added a method to MainConfig.java to get it.
- Added the ItemUtils class to allow item methods to be used elsewhere

**Comment by FireML** [comment]
I will keep this marked as a draft until some more testing is done.

**Comment by FireML** [comment]
Unfortunately no response from the person who said they'd test it. It worked fine when i tested it myself, so i'll mark is as ready.

Any issues will surely be found by people using dev builds.

**Review by sarhatabaot — APPROVED** [review]
lgtm, good job!

**Pull request merged**
